### ISSUE TITLE
[Bug] Portability issue.  Installing tools on NetBSD fails.

### ISSUE THREAD

**Issue by SirWumpus** [ioccc-src/mkiocccentry#1053]
### Is there an existing issue for this?

- [X] I have searched for existing issues and did not find anything like this

### Describe the bug

Installation of the tools fails because of an unknown no-portable option.
```
elf$ gmake install
cc -std=gnu17 -O3 -g3 -pedantic -Wall -Wextra -Wno-char-subscripts -DINTERNAL_INCLUDE  pr_jparse_test.o ../libjparse.a -o pr_jparse_test -L../../dbg -L../../dyn_array -ldyn_array -ldbg

mkiocccentry: make install starting at: Tue Dec 31 15:07:54 EST 2024

gmake --no-print-directory -C test_ioccc install C_SPECIAL="-DINTERNAL_INCLUDE"
install -v -d -m 0775 /usr/local/share/man/man1
install: unknown option -- v
usage: install [-Ubcprs] [-M log] [-D dest] [-T tags] [-B suffix]
           [-a aftercmd] [-f flags] [-m mode] [-N dbdir] [-o owner] [-g group]
           [-l linkflags] [-h hash] [-S stripflags] file1 file2
       install [-Ubcprs] [-M log] [-D dest] [-T tags] [-B suffix]
           [-a aftercmd] [-f flags] [-m mode] [-N dbdir] [-o owner] [-g group]
           [-l linkflags] [-h hash] [-S stripflags] file1 ... fileN directory
       install -d [-Up] [-M log] [-D dest] [-T tags] [-a aftercmd] [-m mode]
           [-N dbdir] [-o owner] [-g group] directory ...
gmake[1]: *** [Makefile:551: install_man] Error 1
gmake: *** [Makefile:1613: install] Error 2
elf$
```

### What you expect

For success (and world domination).

### Environment

- OS: NetBSD 10.1 VM
- Device: Windows 10 Home running VirtualBox 7.0.22
- Compiler: gcc (nb3 20231008) 10.5.0

**Comment by xexyl** [comment]
Oh not this again ...

Do you not have GNU install?

Anyway (yes it's inconvenient but it should work):

```sh
make INSTALL_V= install
```

**Comment by xexyl** [comment]
> Oh not this again ...
> 
> Do you not have GNU install?
> 
> Anyway (yes it's inconvenient but it should work):
> 
> ```shell
> make INSTALL_V= install
> ```

You could also add a Makefile.local to the respective directories with:

```makefile
INSTALL_V=
```

(I think that should work.)

**Comment by SirWumpus** [comment]
> Do you not have GNU install?

GNU make.  Yes.  I invoked it using `gmake install` above.

What does `install -v` do on Linux?

**Comment by xexyl** [comment]
And the 'not this again': I meant the NetBSD problems, not you bringing them up It seems it has a lot of issues. Anyway hopefully the above helps even if it's not very convenient. The `-v` option is pretty useful after all. Anyway: I hope you know I did not mean that dismissively or that I'm blaming you; I just remember other problems with NetBSD. It's good you're reporting them!

I don't know what we could do though.

**Comment by xexyl** [comment]
> > Do you not have GNU install?
> 
> GNU make. Yes. I invoked it using `gmake install` above.
> 
> What does `install -v` do on Linux?

In linux and macOS it's verbosity. Much like `mv -v` and `cp -v`.

**Comment by lcn2** [comment]
We have not released version 2.3 of this repo, so this can be addressed or that release.

**Comment by xexyl** [comment]
What do you propose is done Landon? If we have a way to do it I'm happy to help (as you assigned it to me). I just don't know what we can do without having the `-v` option by default which is a pretty nice default.

Unless .. I wonder. Maybe we could modify the is_available.sh script and decide which way to go about it ?

**Comment by SirWumpus** [comment]
> It seems it has a lot of issues.

I do NOT use Linux as a rule.  NetBSD is my primary development platform for about 15 years, followed by FreeBSD.  Linux I try to avoid - its like the Baskin Robbins of computing.

**Comment by SirWumpus** [comment]
I would have thought the simple solution is just NOT use `-v`.  Is the information necessary?  Probably redundant warm fuzzies.

**Comment by lcn2** [comment]
NetBSD's `install(1)` has not kept up with its instal tool unfortunately, @xexyl, so we recommend dropping the `-v` flag when using `install(1)`.

**Comment by xexyl** [comment]
> I would have thought the simple solution is just NOT use `-v`. Is the information necessary? Probably redundant warm fuzzies.

Well I quite like it personally. I think it's good to let the user know what's been done to their system!

**Comment by lcn2** [comment]
> What do you propose is done Landon? If we have a way to do it I'm happy to help (as you assigned it to me). I just don't know what we can do without having the `-v` option by default which is a pretty nice default.
> 
> Unless .. I wonder. Maybe we could modify the is_available.sh script and decide which way to go about it ?

We recommend dropping the use of `-v` because a number of BSD systems have not key up with changes to `install(1)`.

**Comment by xexyl** [comment]
> > What do you propose is done Landon? If we have a way to do it I'm happy to help (as you assigned it to me). I just don't know what we can do without having the `-v` option by default which is a pretty nice default.
> > Unless .. I wonder. Maybe we could modify the is_available.sh script and decide which way to go about it ?
> 
> We recommend dropping the use of `-v` because a number of BSD systems have not key up with changes to `install(1)`.

That's really unfortunate. I think it's good to let the user know what is done to their system.

What do you think of using is_available.sh to determine if `-v` will work and if it won't drop it? If that will work I think it'd be better.

**Comment by xexyl** [comment]
Please, @SirWumpus, do:

```sh
install -v ; echo $?
```

(or whatever the variable for your exit code of previous command is in your shell.)

It might be that we can workaround it rather than just remove it. If not then we'll have to but it would be nice. I never like not seeing what is done to a system directory and I think it's a shame that some versions of `install(1)` do not actually have that option.

**Comment by SirWumpus** [comment]
> I just remember other problems with NetBSD

Well its my bad for not trying to install the tools before now.  Never thought it would bring on a Spanish Inquisition.  I figured I'd be using the tools by simply adding the tools' `bin/` to my `PATH` and avoid installation into `/usr/local`.  But that is a different discussion.

**Comment by SirWumpus** [comment]
Much of the same output as from the OP.

```
elf$ install -v ; echo $?
install: unknown option -- v
usage: install [-Ubcprs] [-M log] [-D dest] [-T tags] [-B suffix]
           [-a aftercmd] [-f flags] [-m mode] [-N dbdir] [-o owner] [-g group]
           [-l linkflags] [-h hash] [-S stripflags] file1 file2
       install [-Ubcprs] [-M log] [-D dest] [-T tags] [-B suffix]
           [-a aftercmd] [-f flags] [-m mode] [-N dbdir] [-o owner] [-g group]
           [-l linkflags] [-h hash] [-S stripflags] file1 ... fileN directory
       install -d [-Up] [-M log] [-D dest] [-T tags] [-a aftercmd] [-m mode]
           [-N dbdir] [-o owner] [-g group] directory ...
1
```

**Comment by xexyl** [comment]
> > I just remember other problems with NetBSD
> 
> Well its my bad for not trying to install the tools before now. Never thought it would bring on a Spanish Inquisition. I figured I'd be using the tools by simply adding the tools' `bin/` to my `PATH` and avoid installation into `/usr/local`. But that is a different discussion.

Oh don't worry about it. I was just kind of dumbfounded that it would not support `-v`. Not a big deal.

**Comment by SirWumpus** [comment]
One of the reasons I develop on NetBSD is that I find if it works here, the likely hood of it working on other BSDs and Linux is very high (not counting event APIs & libraries), since I try to code to SUS.

Note that `install(1)` is NOT part of SUS.

**Comment by xexyl** [comment]
Hmm ... the problem with the is_available idea is that if an option is supported it requires (of course) a file to install. Thus if `-v` is available the test fails. That's really unfortunate.

I just updated the jparse repo .. now this one ..  Note that the dyn_array and dbg repo still have this but since mkiocccentry install rule does not use make install in those directories it should be okay for now ...

**Comment by xexyl** [comment]
Unless I made a mistake commit https://github.com/ioccc-src/mkiocccentry/pull/1054/commits/f59ed2d174fd5a49b05b5b6e7a96bc48888ac3d9 should do it.

I had to update the bug report script too as that also uses the variable.

**Comment by lcn2** [comment]
> > I would have thought the simple solution is just NOT use `-v`. Is the information necessary? Probably redundant warm fuzzies.
> 
> Well I quite like it personally. I think it's good to let the user know what's been done to their system!

# WARNING: BSD EDITORIAL BELOW

## PERSONAL NOTE BY LANDON - NOT AN IOCCC SUPPORTED STATEMENT

Yes, it is sad: especially since BSD was the one that promoted the `install(1)` tool.  I do recall making improvements to this utility during the 4.1c BSD days.

BSD has fallen behind with a number of shell tools and in some cases the libc / libm API: for some reason some of the maintainers have not kept up with a number of useful improvements to common command line tools.  True, not all changes are "improvements": nevertheless BSD continues to fall farther and farther behind in functionality since the days of 4.4 BSD.

If I had more time, I'd help work on a "4.5 BSD release" implementing a number good ideas from various other UNIX distributions.  **NOT** to turn BSD into "Linux", but rather to modernize some of the basic command line tools as libc / libm APIs.  On the other hand I know that certain people who "dominate" certain flavors of BSD would not accept some mods, further fracturing the BSD distribution world.

It is sad that this seems to be the fate of BSD .. becoming less and less of an option for people to consider supporting and driving people into some "Linux" distributions.  I predict that if BSD continues to fall behind, by the time 2030 rolls around, most applications will consider BSD to not be a valid target.  If that becomes true (and I fear "when that becomes true"), this would be a sad thing.   :-( :-( :-(  

Here I, **LANDON**, a, speaking as someone who has received a "Unix flame award" for my BSD contributions.    Here I am speaking as someone who has been a keynote speaker at a BSD world conference (there I "whacked BSD on the nose with a newspaper" (as the expression goes) on the topic of security -- Yes "who you know" was there and our "outside the conference hall" +discussion" went as well as you might expect.  IMNO, his ego and cult of personally represent a significant security threat to BSD).

I'm **NOT** a Linux fan, nor a macOS fan.  But the lack of improvement in the BSD world has compelled me to convert the last of my BSD hosts into a non-BSD system.  I wish that was not the case.

Very sad.  :-( :-( :-(

At least, BSD is **NOT** System V.  :-) :-) :-)

## BSD OF PERSONAL NOTE BY LANDON

## END OF BSD EDITORIAL

The IOCCC does intend to support BSD systems in installing the code for this repo for IOCCC28.

**Comment by xexyl** [comment]
Interesting comments .. I have to read and reply another time .. have to go really soon for the day.

**Comment by SirWumpus** [comment]
@lcn2 That is sad state of affairs.
> The IOCCC does intend to support BSD systems in installing the code for this repo for IOCCC28.

But this is a little heavy handed when for lack of an "informational" option to drop support.

**Comment by xexyl** [comment]
> > > I would have thought the simple solution is just NOT use `-v`. Is the information necessary? Probably redundant warm fuzzies.
> > 
> > 
> > Well I quite like it personally. I think it's good to let the user know what's been done to their system!
> 
> TL:DR: **The IOCCC does intend to support BSD systems in installing the code for this repo for IOCCC28.**
> 
> # WARNING: BSD EDITORIAL BELOW
> ## PERSONAL NOTE BY LANDON - NOT AN IOCCC SUPPORTED STATEMENT
> Yes, it is sad: especially since BSD was the one that promoted the `install(1)` tool. I do recall making improvements to this utility during the 4.1c BSD days.
> 
> BSD has fallen behind with a number of shell tools and in some cases the libc / libm API: for some reason some of the maintainers have not kept up with a number of useful improvements to common command line tools. True, not all changes are "improvements": nevertheless BSD continues to fall farther and farther behind in functionality since the days of 4.4 BSD.
> 
> If I had more time, I'd help work on a "4.5 BSD release" implementing a number good ideas from various other UNIX distributions. **NOT** to turn BSD into "Linux", but rather to modernize some of the basic command line tools as libc / libm APIs. On the other hand I know that certain people who "dominate" certain flavors of BSD would not accept some mods, further fracturing the BSD distribution world.
> 
> It is sad that this seems to be the fate of BSD .. becoming less and less of an option for people to consider supporting and driving people into some "Linux" distributions. I predict that if BSD continues to fall behind, by the time 2030 rolls around, most applications will consider BSD to not be a valid target. If that becomes true (and I fear "when that becomes true"), this would be a sad thing. :-( :-( :-(
> 
> Here I, **LANDON**, a, speaking as someone who has received a "Unix flame award" for my BSD contributions. Here I am speaking as someone who has been a keynote speaker at a BSD world conference (there I "whacked BSD on the nose with a newspaper" (as the expression goes) on the topic of security -- Yes "who you know" was there and our "outside the conference hall" "_discussion_" went as well as you might expect. IMNO, his ego and cult of personally represent a non-trivial security threat to BSD).
> 
> I'm **NOT** a Linux fan, nor a macOS fan. But the lack of improvement in the BSD world has compelled me to convert the last of my BSD hosts into a non-BSD system. I wish that was not the case.
> 
> Very sad. :-( :-( :-(
> 
> At least, BSD is **NOT** System V. :-) :-) :-)
> 
> ## BSD OF PERSONAL NOTE BY LANDON
> ## END OF BSD EDITORIAL
> **The IOCCC does intend to support BSD systems in installing the code for this repo for IOCCC28.**

It is sad yes. And I do know know who you refer to. Good idea to not name them. I know there is a lot of controversy about them too.

I moved away from FreeBSD for what you said: not as good of a libc. It was a mare for a project I was part of. Had to change code, make workarounds, use ifdef guards, use `%qd` instead of `%lld` and many others.

We can only hope it doesn't regress even further but it seems like it is. It is very sad. My immediate thought is sockets. That'll surely have to at least stay. 

Normally I'd probably say more but should be going.

**Comment by lcn2** [comment]
> @lcn2 That is sad state of affairs.
> 
> > The IOCCC does intend to support BSD systems in installing the code for this repo for IOCCC28.
> 
> But this is a little heavy handed when for lack of an "informational" option to drop support.

Perhaps you misread the statement, @SirWumpus .. Compiling and install on BSD systems **IS** one of our intended targets for IOCCC28, and we appreciate this bug report.

**Comment by xexyl** [comment]
@SirWumpus does the commit I just made take care of this problem? Though I forgot to sync dbg and dyn array repos. Let me do that ... if it's not merged yet. Otherwise maybe Landon can do that.

**Comment by xexyl** [comment]
Oh I just committed the updates .. and you merged. I need to get going. Can you do it instead for me please?

**Comment by lcn2** [comment]
> Oh I just committed the updates .. and you merged. I need to get going. Can you do it instead for me please?

We will do that, @xexyl

**Comment by xexyl** [comment]
> > Oh I just committed the updates .. and you merged. I need to get going. Can you do it instead for me please?
> 
> We will do that, @xexyl

Thanks and good day!

Happy new year to you both! Stays safe! Leaving for the day. BCNU both!

**Comment by lcn2** [comment]
We are testing the combined update AND testing `make all.update_from_clone`.

We also put a "fail if there is a `-v` into an install in our $PATH" to simulate the BSD `install(1)`.  The `make install` appears to work correctly.

**Comment by lcn2** [comment]
Given the above, we will close this as fixed.

Should there be something we missed, @SirWumpus, we would be happy to reopen this bug.

**Comment by SirWumpus** [comment]
> > @lcn2 That is sad state of affairs.
> > > The IOCCC does intend to support BSD systems in installing the code for this repo for IOCCC28.

/me Needs to clean glasses.

> > 
> > 
> > But this is a little heavy handed when for lack of an "informational" option to drop support.
> 
> Perhaps you misread the statement, @SirWumpus .. Compiling and install on BSD systems **IS** one of our intended targets for IOCCC28, and we appreciate this bug report.

**Comment by SirWumpus** [comment]
```
elf$ gmake
elf$ gmake install

mkiocccentry: make install starting                                                                                             
gmake --no-print-directory -C test_ioccc install C_SPECIAL="-DINTERNAL_INCLUDE"
install  -d -m 0775 /usr/local/share/man/man1                                                                                   install  -m 0444 man/man1/fnamchk.1  /usr/local/share/man/man1
install  -d -m 0775 /usr/local/share/man/man8
install  -m 0444 man/man8/chkentry_test.8 man/man8/ioccc_test.8 man/man8/iocccsize_test.8 man/man8/mkiocccentry_test.8 man/man8/
txzchk_test.8 man/man8/hostchk.8 man/man8/ioccc_test.sh.8 man/man8/prep.8 man/man8/prep.sh.8 man/man8/utf8_test.8  /usr/local/sh
are/man/man8

test_ioccc: make install starting

install  -d -m 0775 /usr/local/bin
install  -m 0555 prep.sh hostchk.sh utf8_test fnamchk /usr/local/bin

test_ioccc: make install ending
gmake --no-print-directory -C soup install C_SPECIAL="-DINTERNAL_INCLUDE"
install  -d -m 0775 /usr/local/share/man/man1
install  -m 0444 man/man1/bug_report.1 man/man1/bug_report.sh.1 man/man1/chkentry.1 man/man1/iocccsize.1 man/man1/mkiocccentry.1
 man/man1/txzchk.1 man/man1/location.1  /usr/local/share/man/man1
install  -d -m 0775 /usr/local/share/man/man8
install  -m 0444 man/man8/all_sem_ref.8 man/man8/reset_tstamp.8 man/man8/run_usage.8 man/man8/vermod.8  /usr/local/share/man/man
8

soup: make install starting

install  -d -m 0775 /usr/local/lib
install  -m 0444 soup.a /usr/local/lib
install  -d -m 0775 /usr/local/bin
install  -m 0555 run_usage.sh vermod.sh reset_tstamp.sh all_sem_ref.sh location /usr/local/bin

soup: make install ending
install  -d -m 0775 /usr/local/bin
install  -m 0555  mkiocccentry iocccsize txzchk chkentry /usr/local/bin

mkiocccentry: make install ending
elf$ echo $?
0
elf$
```
It appears to install fine now.

**Comment by lcn2** [comment]
Thank you @SirWumpus and thanks for this bug report.

**Comment by xexyl** [comment]
> > > @lcn2 That is sad state of affairs.
> > > > The IOCCC does intend to support BSD systems in installing the code for this repo for IOCCC28.
> 
> /me Needs to clean glasses.

/me remembers IRC.
/me has worn glasses since 13mo old

.. and I had my first eye surgery at 17mo old and my third by the time I was 9 and that's all they could do. My glasses need to be clean often but I don't have that as a valid excuse. According to my dear cousin I'm blind .. and she's not too far off.

Hope your vision is not that bad (if you weren't being silly and you really do have glasses). For me what matters is I can see. Not everyone can.

Anyway I'm glad this issue is resolved even if it's only (for now) a workaround.
