### ISSUE TITLE
Use tar options to disable including of the username/group in the archive.

### ISSUE THREAD

**Issue by ilyakurdyukov** [ioccc-src/mkiocccentry#13]
Check the binary content of these archives: 
```
$ tar -cf test.tar README.md
$ hexdump -C test.tar

$ tar --numeric-owner --owner=0 --group=0 -cf test.tar README.md
$ hexdump -C test.tar

# aliases: --old-archive, --portability, --format=v7
$ tar --format=v7 -cf test.tar README.md 
$ hexdump -C test.tar
```

**Comment by lcn2** [comment]
Sadly @ilyakurdyukov, the --owned and --group are not found on several distributions.  However --numeric-owner appears to be fairly common.  With just --numeric-owner by itself, the ASCII username and group no longer are stored.  And while we don't 'peak', knowing the UID and GID doesn't say anything useful without the authorship.

On the extraction side, we don't extract as root :-), and we can use --no-same-owner.

**Comment by lcn2** [comment]
The use of --format=v7 appears to have a similar effect as just using -numeric-owner, @ilyakurdyukov so we wonder which is more common.  Any ideas?

**Comment by lcn2** [comment]
We presume that --format=v7 is fairly common now. @ilyakurdyukov and use of it has several effects:

1. No symbolic ownership: the same effect as --numeric-owner
2. Maximum value of user or group ID is limited to 7777777 octal
3. No store special files: no block devices, no character devices, no fifo devices, etc.
4. Max length of a file name is 99 characters

Perhaps  --format=v7 should used instead of just -numeric-owner?

**Comment by lcn2** [comment]
Given the benefits of the more restrictive --format=v7, we will use that in the next release (version 0.27 2022-01-17).

We hope this helps.
