### ISSUE TITLE
Proposal: Merge mkiocccentry and iocccsize repositories

### ISSUE THREAD

**Issue by vog** [ioccc-src/mkiocccentry#3]
I propose to merge the mkiocccentry and iocccsize repositories into a single repository such as "ioccctools", also combining their Makefiles.

This would have several advantages:

1. Contestants just need a single "git clone" and a single "make" rather than having to clone and compile each IOCCC tool individually.
2. Each work into improving the Makefile would automatically benefit all tools.
   * This would avoid situations such as [iocccsize#1](https://github.com/ioccc-src/iocccsize/issues/1), where the Makefile of iocccsize has some flaw that was apparantly already fixed in the Makefile of mkiocccentry.
3. People who just want to try a single tool would automatically build all other tools, so all tools will be compiled on more systems, leading to more information about issues of different platforms.
4. The "iocccsize" option of "mkiocccentry" could become optional (just like `-l ls` and similar options), because we'd now have a proper default path to look at (`dirname(argv[0])`).

**Comment by lcn2** [comment]
We like your idea and agree.

We plan to import the iocccsize.c source into the mkiocccentry and take down the iocccsize repo (to avoid duplicate source).  That way there is a single repo that people need to clone.

We will also arrange for the mkiocccentry tool to compile the core of iocccsize into mkiocccentry so that
mkiocccentry does not need to execute iocccsize to measure prog.c Rule 2b size.  There will STILL be an
independent iocccsize executable that the Makefile will build: we will still make the iocccsize tool, it will
just become a part of this repo AND mkiocccentry will be able to compile in the Rule 2b size measuring
services it needs.

**Comment by lcn2** [comment]
While we have not yet allowed mkioccentry to compile the relevant Rule 2b iocccsize functions into itself, we have completed the merge as requested.

Thank you @vog for your suggestion!
