### ISSUE TITLE
Bug: mkiocccentry-test.sh fails - update after pull request #37 needed

### ISSUE THREAD

**Issue by lcn2** [ioccc-src/mkiocccentry#44]
As expected after pull request #37, the `mkiocccentry-test.sh` test now fails.

This issue was placed in note that there are modifications that are needed to finish pull request #37

**Comment by lcn2** [comment]
> @lcn2 Please merge it. Once that's done I'll fetch upstream on my fork and then commit my changes and make a pull request.

This was expected and so issue #44 has been created to track the issue.  We presume this will be addressed in your future pull request, @xexyl.

**Comment by xexyl** [comment]
This was Ilya’s thing. I know he’s pretty stressed right now and I haven’t heard anything from him for a few days. 

I am not sure if it’s because I upset him (I understand his perspective and I have apologised and I know exactly how it happened so I will be sure to try and prevent that from ever happening again) - which might just be an unnecessary fear or something like that - or if he simply is taking a break but I told him I would let him be until he’s ready. 

Tomorrow if I can I will have a look at the script though and see if I can fix it (assuming he doesn’t before that). 

And now I really am going to sleep! I am going to put the phone down to be sure if it. Will react to the rest tomorrow. 

Good night!

**Comment by xexyl** [comment]
Although I noted it elsewhere this has been fixed. It's no longer possible to do e.g. ``./mkiocccentry .... < answers`` due to the version tag and EOF marker. 

I also made sure that warnings were confirmed/ignored by doing `yes | ...` so that the test will work even if more warnings are generated by the files (they shouldn't be since it's the same files but just in case).

**Comment by lcn2** [comment]
Fixed the test code in #ffd0fe8d8373912b99bc7fd3808f6cd47b97e966 (mkiocccsize v0.33 2022-02-03).

Although the test is not as complex, at least it is consistent with the code now.
