### ISSUE TITLE
Enhancement: add parsed boolean to the JSON parser

### ISSUE THREAD

**Issue by lcn2** [ioccc-src/mkiocccentry#752]
The following valid JSON:

```json
1e1000000
```

is not correctly parsed by the JSON parser.  This is because as of "JSON parser version: 1.0.10 2023-06-29" there is an assumption that if a JSON node cannot be converted into a hardware value, it is not valid JSON.  This assumption is not correct in the case of JSON numbers.

In the case of `struct json_number`, there is a case where JSON can be parsed but not converted into a machine value.  Passing big numbers across the wire in JSON has merit for applications that can use them, or for those applications that don't care about the numeric value. For code that receives such an unconvertible number, the code could still process the string, or such application might be using a multi-precision library allowing the application to convert the JSON number string into a form that it can use.

We do **NOT** propose to add the conversion of big numbers via some multi-precision library.  Such a big number conversion can be said to be beyond the scope of a JSON parser.

We propose to add a boolean `parsed` to all "struct json_foo" in `jparse/json_parse.h` indicating if the given JSON node represents a valid parsed JSON.  The `converted` boolean would continue its current meaning.  In all cases, if `parsed` is set to false, `converted` will be set to false. 

Existing code that tests the `converted` boolean would be examined to determine if it should instead use `parsed`.  Such code points would need to be examined "by hand".

Functions such as  `json_process_decimal()` and `json_process_floating()` would continue to work as the do now in converting values.

The `is_decimal()` function works for big number integers of any size now, so that would continue be used as it is. A new function `is_floating_notation()` would be added to do similar character checking for floating strings and `is_e_notation()` for e-notation strings: both will work for big numbers of any size. 

Code that calls those functions such as `json_conv_number()` would still set `converted` boolean to false it they were not able to convert to a machine numerical value as they do now. The `parsed` boolean value would be based on the returns from `is_decimal()` and the new `is_floating_notation()` and the use `is_e_notation()`. Thus the `parsed` boolean would be set independently of it the  `json_process_decimal()` and `json_process_floating()` were able to set `converted` to true or false.

A `sem_node_valid_parsed()` function, along the lines of `sem_node_valid_converted()` would be added.  Code that called `sem_node_valid_converted()` would be examined to determine if it should call `sem_node_valid_parsed()` instead.

JSON debug code that printed information about a JSON number would be enhanced to be able to handle the case where a `struct json_number` that had `parsed` as true but `converted` was false.

As for JSON values such as JSON boolean, JSON strings and JSON null, the setting of `parsed` will be the same as `converted`.  The same would apply to the compound JSON items such as JSON members, JSON arrays, JSON objects and JSON elements.

Other existing code that uses the `jparse.a` world be examined and where need modified to deal with the distinction between a parsed JSON node and a node that was able to be converted into some sort of machine value.

Documentation will need to be updated to account for this change.

**Comment by xexyl** [comment]
> The following valid JSON:
> 
> ```json
> 1e1000
> ```
> 
> is not currently parsed by the JSON parser, jparse. This is because as of "JSON parser version: 1.0.10 2023-06-29" there is an assumption that if a JSON node cannot be converted, it is not valid JSON.

Well I wouldn't put it that way but it can certainly appear to be that way yes. 

> 
> In the case of `struct json_number`, this need not be the case. Passing big numbers across the wire in JSON has merit for applications that can use them, or for those applications that don't care about the numeric value. For code that receives such an unconvertible number, the code could still process the string. And programs that use big numbers could be given the string and do with it what they wish.
> 
> We do **NOT** propose to add the conversion of big numbers via some multi-precision library. Such a big number conversion cab be said to be beyond the scope of a JSON parser.
> 
That's good.

> We propose to add a boolean `parsed` to all "struct json_foo" in `jparse/json_parse.h` indicating if the given JSON node represents a valid parsed JSON. The `converted` would retain its meaning as a boolean is not. Existing code that tests the `converted` boolean would be examined to determine if it should instead use `parsed`.
> 

> A `sem_node_valid_parsed()` function, along the lines of `sem_node_valid_converted()` would be added. Code that called `sem_node_valid_converted()` would be examined to determine if it should call `sem_node_valid_parsed()` instead.
> 
> JSON debug code that printed information about a JSON number would be enhanced to be able to handle the case where a `struct json_number` that had a `parsed` as true but `converted` was false.
> 
> Other existing code that uses the `jparse.a` world be examined and where need modified to deal with the distinction between a parsed JSON node and a node that was able to be converted into some sort of machine value.

I guess this means that the code would check that it looks like a floating point/exponent (or in the case of other types then whatever type) and then if it can't convert it it would make it like a string? I'm not sure entirely what you're after but given the complexity maybe you want to address it?

**Comment by xexyl** [comment]
> The [top comment](https://github.com/ioccc-src/mkiocccentry/issues/752#issue-1803439546) has been modified.

I meant to say: I'd be happy to do documentation if nothing else.

**Comment by lcn2** [comment]
> I guess this means that the code would check that it looks like a floating point/exponent (or in the case of other types then whatever type) and then if it can't convert it it would make it like a string? I'm not sure entirely what you're after but given the complexity maybe you want to address it?

Functions such as ` json_process_decimal()` and `json_process_floating()` would continue to work as the do now in converting values.

The `is_decimal()` function works for big number integers, so that would be used. A new function `is_float()` would be added to do similar character checking for floating and exp strings that would also work for big numbers.

Code that calls those functions such as `json_conv_number()` would still set `converted` to false it they were not able to convert to a machine numerical value as they do now.    The `parsed` boolean value would be based on the returns from  `is_decimal()` and the new `is_float()`.  Thus the `parsed` boolean would be set independently of it the ` json_process_decimal()` and `json_process_floating()` were able to set `converted` to true or false.

**Comment by lcn2** [comment]
>> is not currently parsed by the JSON parser, jparse. This is because as of "JSON parser version: 1.0.10 2023-06-29" there is an assumption that if a JSON node cannot be converted, it is not valid JSON.
>>
> Well I wouldn't put it that way but it can certainly appear to be that way yes.

The [top comment](https://github.com/ioccc-src/mkiocccentry/issues/752#issue-1803439546) has been modified again.

**Comment by xexyl** [comment]
> JSON debug code that printed information about a JSON number would be enhanced to be able to handle the case where a `struct json_number` that had a `parsed` as true but `converted` was false.
> 
> As for JSON values such as JSON boolean, JSON strings and JSON null, the setting of `parsed` will be the same as `converted`. The same would apply to the compound JSON items such as JSON members, JSON arrays, JSON objects and JSON elements.
> 
> Other existing code that uses the `jparse.a` world be examined and where need modified to deal with the distinction between a parsed JSON node and a node that was able to be converted into some sort of machine value.
> 

I was thinking at first that it would need a string node but I forgot. It has a string that originally was what triggered the parsing. So then if it failed to convert it but it is valid the code would have to show that string instead?

**Comment by lcn2** [comment]
In all cases for the tool and the `chkentry(1)` tool and related IOCCC tools, use of `converted` will be sufficient as such tools that parse JSON or check JSON numbers need to use the converted value as well.

**Comment by xexyl** [comment]
> In all cases for the tool and the `chkentry(1)` tool and related IOCCC tools, use of `converted` will be sufficient as such tools that parse JSON or check JSON numbers need to use the converted value as well.

... as long as the tools only check for validity of the file. But what happens if it needs to do more? What happens also with the new tool when it is expected to print out numbers but it can't? Well I guess it just means the boolean is checked and it prints the string instead of the number?

I'll be doing other things now. Having a kind of off day. I'm sure I'll be able to do more tomorrow though I did not finish what I started today either so I'll have to spend a bit of time doing that as well.

**Comment by lcn2** [comment]
In examining the code points that use the `converted` boolean: before we edit them, will consider writing macros or utility functions that will help such code point do the right thing with unusable JSON nodes.

**Comment by xexyl** [comment]
> In examining the code points that use the `converted` boolean: before we edit them, will consider writing macros or utility functions that will help such code point do the right thing with unusable JSON nodes.

Sounds like a good idea! I hope to tomorrow look at the document you committed and fix any typos and then ask questions / make comments.

**Comment by xexyl** [comment]
... leaving for the day. Good luck with this! I'll do more tomorrow in some form or another I am sure. Good day!

**Comment by lcn2** [comment]
> ... leaving for the day. Good luck with this! I'll do more tomorrow in some form or another I am sure. Good day!

We are going to focus on generating JSON for the new-winners repo .. while the idea for this simmers as it is not a high priority.

Nevertheless we think the version numbers, when this enhancement is done, will need to be bumped to the 1.1 level as this represents a notable change to the API.

**Comment by xexyl** [comment]
> > ... leaving for the day. Good luck with this! I'll do more tomorrow in some form or another I am sure. Good day!
> 
> 
> 
> We are going to focus on generating JSON for the new-winners repo .. while the idea for this simmers as it is not a high priority.
> 
> 

Sounds good. 
> 
> Nevertheless we think the version numbers, when this enhancement is done, will need to be bumped to the 1.1 level as this represents a notable change to the API.

Good idea.

**Comment by xexyl** [comment]
I'm working on what will I believe make this easier for you to finish. Initially `make prep` failed due to not updating the jnum (which macOS tried to change to 'junk' which seems fitting for JSON :-) :-) ) check data but after updating the gen file that does this and running it and then running make prep it seems okay so I'll do a commit.

I also incidentally came across a parse function which did not set the `converted` boolean to false after the calloc()! That function is `json_conv_null()` but now it does do that. Added placeholder functions for the ones you referred to that need to be written as well. Those are NOT called as it could mess up whether it's an e notation or floating point notation. I added a number of XXX comments here. I'll do more in the log after updating the CHANGES.md and the version of the json parser and jparse.

I believe that this will help you out though. I've not updated the man page: I figure we can wait until this is completed before that's done.

**Comment by xexyl** [comment]
> I'm working on what will I believe make this easier for you to finish. Initially `make prep` failed due to not updating the jnum (which macOS tried to change to 'junk' which seems fitting for JSON :-) :-) ) check data but after updating the gen file that does this and running it and then running make prep it seems okay so I'll do a commit.
> 
> I also incidentally came across a parse function which did not set the `converted` boolean to false after the calloc()! That function is `json_conv_null()` but now it does do that. Added placeholder functions for the ones you referred to that need to be written as well. Those are NOT called as it could mess up whether it's an e notation or floating point notation. I added a number of XXX comments here. I'll do more in the log after updating the CHANGES.md and the version of the json parser and jparse.
> 
> I believe that this will help you out though. I've not updated the man page: I figure we can wait until this is completed before that's done.

See commit https://github.com/ioccc-src/mkiocccentry/pull/753/commits/f75cecd609d9092f655d061d61b2f41de7722750!

**Comment by xexyl** [comment]
Just wrote those functions for checking floating notation and e notation[0] .. thought you might or might not want to improve it. I did not check all XXX comments and I also did not update what we consider to be floating point or e notation. As well if e notation was detected the `is_floating` was not set to true but it should be, right? It has to have a `.` to be floating point? Perhaps you'd like to look at the XXX comments?

`make prep` passes fine. Again after regenerating the test files. Strange thing: it seemed that the boolean for whether or not it has a '.' in it was not correct. It seems the same for 'e' found. I'm not sure if that was done in the last commit or not but I don't think so. It _appears_ to be correct now. 

Multiple dots have been tested against now.

See commit https://github.com/ioccc-src/mkiocccentry/pull/754/commits/7692ef075aa1fc71115da7b7c0f9d62fe14d657a.

This won't completely resolve this issue but it should be a good help in solving it I think.

The functions are probably incomplete and this issue is not complete either I don't think! I am less clear on the rest. Hopefully these two commits will be a good start for you and a googolplex is now parsable at least.

Since you have more to do with the other document I will hold off on reviewing it. I'll look at it after you get that stuff done.

I've updated my devices except macOS: going to do that now. Might do more in the other repo later. I hope that these commits are a good help!

[0] Note that these functions have a lot of the same code as the json process floating checks but that might or might not be correct as it might not be strictly the same tests in C as for json (fewer tests are in the functions for C due to less restrictions but all tests are in the json functions). Maybe you'd like to correct anything further as well?

**Comment by xexyl** [comment]
My updated comments on part of the OP.

> The following valid JSON:
> 
> ```json
> 1e1000000
> ```
> 
> is not correctly parsed by the JSON parser. This is because as of "JSON parser version: 1.0.10 2023-06-29" there is an assumption that if a JSON node cannot be converted into a hardware value, it is not valid JSON. This assumption is not correct in the case of JSON numbers.
> 
Well as of earlier today that is done now. Not everything is done of course.


> We propose to add a boolean `parsed` to all "struct json_foo" in `jparse/json_parse.h` indicating if the given JSON node represents a valid parsed JSON. The `converted` boolean would continue its current meaning. In all cases, if `parsed` is set to false, `converted` will be set to false.
> 

As of earlier today the boolean was added and is used but whether it's correct in every case or not I don't know: I think probably not but I think or numbers it's okay. Certainly checks have to be made to verify this though.

> Existing code that tests the `converted` boolean would be examined to determine if it should instead use `parsed`. Such code points would need to be examined "by hand".
> 
I addressed the points where it is an error if both are false. If both are not false it's assumed that at least it's parsable. Maybe I didn't think of another condition when checking both? I do NOT think that I checked anywhere else.

> Functions such as `json_process_decimal()` and `json_process_floating()` would continue to work as the do now in converting values.
> 

The only difference in `json_process_floating()` is that it now checks for two `.`s which of course is an error. Now the lexer will report an invalid token in that case but I added it as extra sanity check.

> The `is_decimal()` function works for big number integers of any size now, so that would continue be used as it is. A new function `is_floating_notation()` would be added to do similar character checking for floating strings and `is_e_notation()` for e-notation strings: both will work for big numbers of any size.

I did most of what is already in the process functions but fewer checks so that it would work with C too. I might have missed some checks that should not be there too. Since the json process function does the checks too this is okay though. I suspect you will have improvements to the is_ functions.

> 
> Code that calls those functions such as `json_conv_number()` would still set `converted` boolean to false it they were not able to convert to a machine numerical value as they do now. The `parsed` boolean value would be based on the returns from `is_decimal()` and the new `is_floating_notation()` and the use `is_e_notation()`. Thus the `parsed` boolean would be set independently of it the `json_process_decimal()` and `json_process_floating()` were able to set `converted` to true or false.
> 

This is done I believe.

> A `sem_node_valid_parsed()` function, along the lines of `sem_node_valid_converted()` would be added. Code that called `sem_node_valid_converted()` would be examined to determine if it should call `sem_node_valid_parsed()` instead.
> 
This I did not do and I don't know what you have in mind. Would you do this one?

> JSON debug code that printed information about a JSON number would be enhanced to be able to handle the case where a `struct json_number` that had `parsed` as true but `converted` was false.
> 

I'm not sure what you mean here either unless you mean the print functions should have a character indicating it was converted? But that's not debug message. Even so I think the function should be updated. Do you agree?

> As for JSON values such as JSON boolean, JSON strings and JSON null, the setting of `parsed` will be the same as `converted`. The same would apply to the compound JSON items such as JSON members, JSON arrays, JSON objects and JSON elements.
> 
Okay this is not done that way. Want me to update it? I can see the argument this way now because if say the boolean is not `false` and not `true` then it's actually not parsable at all.

> Other existing code that uses the `jparse.a` world be examined and where need modified to deal with the distinction between a parsed JSON node and a node that was able to be converted into some sort of machine value.
> 

The only other code I had to modify was the jnum checks: that should be good unless of course I made a mistake in the logic with converted / parsed: that's entirely possible given the time I did it!

> Documentation will need to be updated to account for this change.

As noted before I'll wait until everything is done and then I'll be happy to do this.

**Comment by lcn2** [comment]
It looks like you have volunteered to finish this issue and permit the jparse to parse JSON numbers of any size. Thanks @xexyl

**Comment by xexyl** [comment]
> It looks like you have volunteered to finish this issue and permit the jparse to parse JSON numbers of any size. Thanks @xexyl

At least some of it! A lot I guess. I'm working on the print function now. Some of it I am unclear about though.

And you're very welcome! I had the inspiration and motivation to do it. However I'll probably be on to other things in a bit - once I make this next commit.

**Comment by lcn2** [comment]
> At least some of it! A lot I guess. I'm working on the print function now. Some of it I am unclear about though.

Well there is more than one way to implement the solution to this enhancement issue. 

We do suggest you look at all places in this repo that use the variables and functions mentioned in the [top comment](https://github.com/ioccc-src/mkiocccentry/issues/752) and consider any macros that might simplify the way code checks if a JSON node is OK. 

When you do finish we recommend you move the version to 1.1.

**Comment by xexyl** [comment]
> > At least some of it! A lot I guess. I'm working on the print function now. Some of it I am unclear about though.
> 
> Well there is more than one way to implement the solution to this enhancement issue.
> 

What I'm entirely unclear about is: `sem_node_valid_parsed()`. But maybe looking at the converted version is all that is needed there. I just reread it and noticed it's not both but a version of the other for parsed not converted.

> We do suggest you look at all places in this repo that use the variables and functions mentioned in the [top comment](https://github.com/ioccc-src/mkiocccentry/issues/752) and consider any macros that might simplify the way code checks if a JSON node is OK.

Macros might be an idea. You said that indeed. Not sure what you had in mind though. Maybe something like (this is quickly and not verified valid syntax - i.e. not typing it here in GitHub):

```c
#define VALID_JSON(item) ((item)->converted || (item)->parsed))
```

or something like that ?

But maybe you were thinking of it doing something else: not sure.
> 
> When you do finish we recommend you move the version to 1.1.

I will.

**Comment by xexyl** [comment]
> > > At least some of it! A lot I guess. I'm working on the print function now. Some of it I am unclear about though.
> > 
> > 
> > Well there is more than one way to implement the solution to this enhancement issue.
> 
> What I'm entirely unclear about is: `sem_node_valid_parsed()`. But maybe looking at the converted version is all that is needed there. I just reread it and noticed it's not both but a version of the other for parsed not converted.
> 

The function was added in commit https://github.com/ioccc-src/mkiocccentry/pull/757/commits/cca6b2e237489ae2a2059fc02348b0c70d18c5fd.

Does this need to be called though? I think the places it's called are IOCCC specific and those should be converted too for validity?


> > We do suggest you look at all places in this repo that use the variables and functions mentioned in the [top comment](https://github.com/ioccc-src/mkiocccentry/issues/752) and consider any macros that might simplify the way code checks if a JSON node is OK.
> 
> Macros might be an idea. You said that indeed. Not sure what you had in mind though. Maybe something like (this is quickly and not verified valid syntax - i.e. not typing it here in GitHub):
> 
> ```c
> #define VALID_JSON(item) ((item)->converted || (item)->parsed))
> ```

This was added in commit 496cf6e2d47c71ab3638923b45f99c2cab9ac33f. Maybe more macros should be added? Not sure.

**Comment by xexyl** [comment]
I updated documentation after all. Did I miss anything?

What else has to be done for this issue?

**Comment by xexyl** [comment]
Doing other things now. I'll continue tomorrow if not later today: probably tomorrow. Good day!

**Comment by lcn2** [comment]
> I updated documentation after all. Did I miss anything?
> 
> What else has to be done for this issue?

Perhaps look at:

* [ ] `./jparse/test_jparse/jnum_chk.c`
* [ ] `./jparse/test_jparse/jnum_gen.c`
* [ ] `./jparse/json_util.c`
* [ ] `./jparse/json_sem.c`

to see if the use of `converted` or functions that look at a converted condition need to check `parsed` (or a suitable macro of function) as well.

**Comment by xexyl** [comment]
> > I updated documentation after all. Did I miss anything?
> > What else has to be done for this issue?
> 
> Perhaps, @xexyl, you should look at:
> 
Thanks!

> * [ ]  `./jparse/test_jparse/jnum_chk.c`

This was done yesterday as adding the boolean to the number struct made the order of struct member variables wrong types etc. This prompted the need to run the rebuild rule (as expected) after updating the below one, `jnum_gen.c`. See below.

> * [ ]  `./jparse/test_jparse/jnum_gen.c`

As noted above this one was done yesterday. However I did not have the code check the parsed boolean as well as the already there converted boolean. This has been done but is not yet tested.

> * [ ]  `./jparse/json_util.c`

Done in unpublished commit.

> * [ ]  `./jparse/json_sem.c`
> 

If `node`'s item in `sem_node_valid_converted()` has converted == false should it instead call the parsed version ? Not sure: in the case of numbers it's possible it would be good but in the case of others they should always be the same. Yet maybe it's not desirable to have either or when converted == false. What do you think ?

Or .. another idea: perhaps that function, the converted one, should be renamed to `sem_node_valid` and then if converted == false check `parsed` ?

Actually I think this s should be done because for numbers if converted == false it would be an error even if parsed is true which is not a semantics error, right?

I'll do this but maybe after a rest .. not sure.

> to see if the use of `converted` or functions that look at a converted condition need to check `parsed` (or a suitable macro of function) as well.

I'm not sure what other macros might be useful. Hmmm...  I see though that I did not use the macro in much of the above. That's because the macro checks for `||` and the code checks for `&&` and then also one or the other (in most cases warning that it's not both: except for numbers where it shows that the number is converted or else parsed .. or neither of course).

I improved printing of strings: if converted == true print flag 'c'; else if parsed == true print flag 'p'.

Those files have been modified but let me know what you think. I'll do a pull request after updating versions and CHANGES.md: then I'll see if I can rest. After that I'll change the function above to check both converted and parsed. That'll be in a different pull request in case you want me to change that one!

**Comment by xexyl** [comment]
> > > I updated documentation after all. Did I miss anything?
> > > What else has to be done for this issue?
> > 
> > 
> > Perhaps, @xexyl, you should look at:
> 
> Thanks!
> 
> > * [ ]   `./jparse/test_jparse/jnum_chk.c`
> 
> This was done yesterday as adding the boolean to the number struct made the order of struct member variables wrong types etc. This prompted the need to run the rebuild rule (as expected) after updating the below one, `jnum_gen.c`. See below.
> 
> > * [ ]   `./jparse/test_jparse/jnum_gen.c`
> 
> As noted above this one was done yesterday. However I did not have the code check the parsed boolean as well as the already there converted boolean. This has been done but is not yet tested.
> 
> > * [ ]   `./jparse/json_util.c`
> 
> Done in unpublished commit.
> 
> > * [ ]   `./jparse/json_sem.c`
> 
> If `node`'s item in `sem_node_valid_converted()` has converted == false should it instead call the parsed version ? Not sure: in the case of numbers it's possible it would be good but in the case of others they should always be the same. Yet maybe it's not desirable to have either or when converted == false. What do you think ?
> 
> Or .. another idea: perhaps that function, the converted one, should be renamed to `sem_node_valid` and then if converted == false check `parsed` ?
> 
> Actually I think this s should be done because for numbers if converted == false it would be an error even if parsed is true which is not a semantics error, right?
> 
> I'll do this but maybe after a rest .. not sure.
> 
> > to see if the use of `converted` or functions that look at a converted condition need to check `parsed` (or a suitable macro of function) as well.
> 
> I'm not sure what other macros might be useful. Hmmm... I see though that I did not use the macro in much of the above. That's because the macro checks for `||` and the code checks for `&&` and then also one or the other (in most cases warning that it's not both: except for numbers where it shows that the number is converted or else parsed .. or neither of course).
> 
> I improved printing of strings: if converted == true print flag 'c'; else if parsed == true print flag 'p'.
> 
> Those files have been modified but let me know what you think. I'll do a pull request after updating versions and CHANGES.md: then I'll see if I can rest. After that I'll change the function above to check both converted and parsed. That'll be in a different pull request in case you want me to change that one!

With the exception of the change of the function name and updating it to check for either converted or parsed these were done in commit https://github.com/ioccc-src/mkiocccentry/pull/762/commits/9c40440e60160884f4152fc5d31fbcfc85d45298.

I'm going to try resting now and when I'm back I plan on doing the other change. If that's all that needs to be done when it is done I'll update the version of the release of the parser. Otherwise please let me know what else has to be done or if anything should be changed. Hopefully this can be resolved very soon! Then when you're done with that document I can make fixes and then ask questions and start working on the new tools.

Hope you're sleeping well .. and I hope I can sleep though I seriously doubt it :(

**Comment by xexyl** [comment]
New macros added in commit https://github.com/ioccc-src/mkiocccentry/pull/763/commits/1e4240bf00fd3abe7e695c0eb302bd682dae12ea that check the booleans `converted` and `parsed`.

Now it's really time for a rest. When I'm back I'll check other files and update any necessary to use the macros. Then I'll look at the function change noted above.

**Comment by xexyl** [comment]
With commit https://github.com/ioccc-src/mkiocccentry/pull/764/commits/200f08eb15356bbc1102779aa0fadcd7942491b3 I believe I have fully resolved this but if not: what is missing?

The function change I suggested earlier was done. For numbers it can be either `converted` or `parsed` but for the others it has to be both as they have to both be true for it to be valid.

More use of the macros.

If nothing is missing and this resolves the issue I'll change the version of the json parser and jparse. Let me know please!

**Comment by xexyl** [comment]
I believe that once this is merged this issue can be resolved as complete!

I admit I did not think it was something I was going to be able to do so I'm glad I looked at it yesterday morning. Now we can focus on the new tools. Right now as you're working on the spec I am trying to get the documentation of the funny problems I noticed in the entry from 1986 that I told you about. I'm reconstructing the problem and then forming what I hope will be presented well in the README.md file.
