### ISSUE TITLE
`gmake` on `NetBSD 10.0` fails to build `iocccsize` et al.

### ISSUE THREAD

**Issue by SirWumpus** [ioccc-src/mkiocccentry#875]
On `NeBSD` trying to build 
```
elf$ pwd
/home/achowe/git/ioccc_src/mkiocccentry
elf$ gmake iocccsize
usage: make [-BeikNnqrSstWwX]
            [-C directory] [-D variable] [-d flags] [-f makefile]
            [-I directory] [-J private] [-j max_jobs] [-m directory] [-T file]
            [-V variable] [-v variable] [variable=value] [target ...]
gmake: *** [Makefile:519: soup/soup.a] Error 2
```
Is there something wrong here with NetBSD using `gmake` (vs BSD native `make`).

_Originally posted by @SirWumpus in https://github.com/ioccc-src/mkiocccentry/issues/873#issuecomment-2189269740_

**Comment by SirWumpus** [comment]
Try to build all results in similar failure.
```
elf$ gmake
usage: make [-BeikNnqrSstWwX]
            [-C directory] [-D variable] [-d flags] [-f makefile]
            [-I directory] [-J private] [-j max_jobs] [-m directory] [-T file]
            [-V variable] [-v variable] [variable=value] [target ...]
gmake: *** [Makefile:462: all_dbg] Error 2
```

```
elf$ gmake --version
GNU Make 4.4.1
Built for x86_64--netbsd
```

**Comment by xexyl** [comment]
As I noted in the other issue based on your thought `MAKE` is hard coded as `make`. Not sure if that will matter but if so you could just do something like ...

```sh
make MAKE=gmake
```

or something like that ?

**Comment by xexyl** [comment]
Okay yes the Makefile does indeed use `${MAKE}` so it might very well matter.

**Comment by xexyl** [comment]
```sh
$ make MAKE=bsdmake
bsdmake: illegal option -- -
usage: make [-BPSXeiknqrstv] [-C directory] [-D variable]
	[-d flags] [-E variable] [-f makefile] [-I directory]
	[-j max_jobs] [-m directory] [-V variable]
	[variable=value] [target ...]
make: *** [Makefile:462: all_dbg] Error 2

```

So maybe try what I suggested over there?

**Comment by SirWumpus** [comment]
Yep.  
```
elf$ gmake MAKE=gmake iocccsize
cc -std=gnu11 -O3 -g3 -pedantic -Wall -Wextra  -DMKIOCCCENTRY_USE iocccsize.c -c
cc -std=gnu11 -O3 -g3 -pedantic -Wall -Wextra  iocccsize.o soup/soup.a dbg/dbg.a -o iocccsize
elf$
```
works around the issue.  

Oddly you need the `MAKE` macro set for other targets like `clean`.

**Comment by xexyl** [comment]
> Yep.
> 
> ```
> elf$ gmake MAKE=gmake iocccsize
> cc -std=gnu11 -O3 -g3 -pedantic -Wall -Wextra  -DMKIOCCCENTRY_USE iocccsize.c -c
> cc -std=gnu11 -O3 -g3 -pedantic -Wall -Wextra  iocccsize.o soup/soup.a dbg/dbg.a -o iocccsize
> elf$
> ```
> 
> works around the issue.
> 

Good that it works.

> Oddly you need the `MAKE` macro set for other targets like `clean`.

That's because it uses `make clean` on subdirectories.

**Comment by SirWumpus** [comment]
Also doing a complete build generates lots of `gcc` compiler warnings; `gcc (nb3 20231008) 10.5.0`

Build output...
[build.txt](https://github.com/user-attachments/files/15977333/build.txt)

**Comment by SirWumpus** [comment]
IMO you should ***not*** set `MAKE` macro.  The binary will set it itself, then it would be more portable across platforms.

**Comment by xexyl** [comment]
> IMO you should _**not**_ set `MAKE` macro. The binary will set it itself, then it would be more portable across platforms.

Talk to Landon about that :-)

**Comment by xexyl** [comment]
> Also doing a complete build generates lots of `gcc` compiler warnings; `gcc (nb3 20231008) 10.5.0`
> 
> Build output... [build.txt](https://github.com/user-attachments/files/15977333/build.txt)

.. some of which are annoying and frivolous. It might help to run:

```sh
./bug_report.sh
```

and attach the. log file to see more details.

**Comment by xexyl** [comment]
I guess we could simply disable `-Wchar-subscripts`. No need to worry about that one.

As for:

```c
./jparse.y:832:42: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘yy_size_t’ {aka ‘long unsigned int’} [-Wformat=]
  832 |      json_dbg(JSON_DBG_VVHIGH, __func__, "under json_number: yyleng: <%d>", jparse_get_leng(scanner));
```

My guess is this depends on the system. I know I have in the past tried to fix that kind of warning with typedefs but then another one shows up in a different system. Should we disable that warning, @lcn2 ?

My thinking is that they should be disabled. I don't know how portable `-Wno-format` is though. 

Do you want me to do that or should I focus on what I'm working on?

**Comment by SirWumpus** [comment]
`-Wchar-subscripts` is usually a good one; always a problem with the `ctype` macros.  The alternative for ctype macros is to link with the ctype functions eg. `(isdigit)(of_questionable_characater)`, force by using parens around function name, which makes the binary larger.

Format issues usually need to cast their args to match the format specifier, though you might need `%ld` instead `%d` depending on actual size.

**Comment by lcn2** [comment]
With commit 6486cdb24b5dbbaac81b042df5304975403c5a06 the setting of the `MAKE` makefile variable has been removed.

**Comment by lcn2** [comment]
With commit 8261e7e81282a1f36f1382d2b9cdc26da909da9e we have added -Wno-char-subscripts to C compile lines

**Comment by lcn2** [comment]
How do things look for NetBSD compiling now, @SirWumpus ?

**Comment by SirWumpus** [comment]
A simple ...
```
elf$ gmake clean all test
...
PASSED: test_ioccc/chkentry_test.sh
test_ioccc: PASSED: ioccc_test.sh

test_ioccc: make test ending
rm -f jparse/test_jparse/pr_jparse_test

mkiocccentry: make test ending
elf$
```

Behaves as expected.  Much better.  Still a few compiler warnings, but essentially way better.

**Comment by xexyl** [comment]
> With commit 6486cdb24b5dbbaac81b042df5304975403c5a06 the setting of the `MAKE` makefile variable has been removed.

In that case I will remove it from var.mk in a little bit. Unfortunately I woke up at stupid o'clock again in this case about 1. That was two and a half hours ago. Still sleepy but can't sleep. Unsure if I want to take caffeine yet as I was hoping to be able to push that out a bit longer especially since I have been having a hard time staying awake even at 1600 hours which is too early for me to go to bed. 

Still because I won't have as much time online today due to the planned extended power outage and because I can't sleep I think I will (I just did). Good thing is that I am an ultra rapid metaboliser of caffeine so it should be pretty soon. 

I am glad this issue has been resolved but it seems like another issue might not be? I thought I saw something. 

I want to try finishing the task from yesterday at the very least but I know there are other ones to take care of too. I will look at that other issue soon and see what I see.

**Comment by xexyl** [comment]
Ah .. I see you already took care of it in `var.mk`. Glad you remembered it and could take care of it too (knew you were travelling).

**Comment by SirWumpus** [comment]
> ... due to the planned extended power outage ...

Sleep then?  

We have a planned building power cut tomorrow for 4 hours (10h00 - 14h00).

**Comment by xexyl** [comment]
> > ... due to the planned extended power outage ...
> 
> Sleep then?

Too hot :( .. but thanks for the suggestion. I'll probably be at my auntie's house who lives five minutes away and has air. We're considering going to a bookshop too but that's hard for me since the pandemic started and also another reason of late that makes it hard to be out and about.

The other day the temperature was 7 Celsius higher than the daily average (!!). For months I have been saying that this is going to be a super hot year (and our record is 47 C) and a month or two ago the meteorologists finally started saying that too. Worse is humidity is obviously increasing too and I'm not used to that. Also I have a body temperature regulation issue. So sleep is out of the question I'm afraid.

Thanks though - it's a nice thought but won't work (though as it happens I find I am very uncomfortable sleeping ni the day anyway though I have many times in the past).

> 
> We have a planned building power cut tomorrow for 4 hours (10h00 - 14h00).

Always not nice. Hope it's okay! The power shuts off at 7:30 this morning. At that point I'll shut the server off (it'll be off for 6 hours which is longer than the UPSes can manage) and then the UPSes (one has the monitor and maybe the modem/router and the other the server and RDX drive and such). 

The only good thing with the recent power outages (and the possibility of more power outages due to the heat this year) is that I got a new UPS. Got it cheaper on eBay (by over 100 cheaper) brand new. This time it's a SmartUPS: the APC SmartUPS SMT1500C. More efficient battery and other benefits. `apcupsd` is wonderful and all I'll have to do is reconfigure it slightly (and update the battery date of course!).

It won't last for long power outages but the current battery is ...

```sh
$ apcaccess | grep BATTDATE
BATTDATE : 2019-01-26

```

so more than five years old and this UPS is easy to replace with a newline: the outlet it plugs into in the wall is up higher on the wall and not behind a desk. So with the power outages it's a good time to take care of it anyway since my uptime of almost a year was ruined. My highest uptime was 2 years, 330 days, 23 hours, 29 minutes and 17 seconds but that was years ago and never been able to get higher: due to power outage and other things.

Anyway best wishes on the power outage!

Also - cute doggie! I like bigger dogs myself but it's still a cute doggie and I'm glad he/she has a forever home!
